Added ACOT / AOT Branch Office Holdings
Fragjacker/Acquistion-of-Technology pull request #37
Opened 2024-09-21 10:24 UTC by Xahkarias

Credits to Zombifier (aka Sylph) for the mod, I just updated it with permission.

Delta, Alpha, Phanon, Stellarite versions of the following:
- Mineral holding
- Food holding
- Consumer Goods holding
- Alloy holding
- Naval Cap holding
- Unity holding
- Research holding
- Amenity holding
- Trade boosting holding
- Embassy holding
- Gospel corporation (temple) holding (for the prosperity gospel civic)
- **Criminal Variations are also included for all above**
- Executive Retreat holding
- Xenotourism holding
- Clinic holding (for the pharma state civic)

2024-09-21 10:47 UTC, Fragjacker requested changes

2024-09-21 10:47 UTC, Fragjacker commented on acquistion_of_technology/localisation/english/aot_00_holding_l_english.yml
The entries here need to be copied over to the other languages as well. Otherwise there won't be any text showing up for any other language then english. You can do this automated by using this little helper program here: https://github.com/khoeos/Paradox-mod-language-converter/releases/tag/v1.0.0

2024-09-21 18:29 UTC, Xahkarias commented on acquistion_of_technology/localisation/english/aot_00_holding_l_english.yml
Fixed in https://github.com/Fragjacker/Acquistion-of-Technology/pull/37/commits/3922a260df9635228cbe9bb4c2107bbc56a4ce33

2024-09-22 11:56 UTC, Fragjacker approved these changes

2024-09-22 11:57 UTC, merged